alter table CUSTOMERORDERMANAGEMENT_REQUEST_LINE add column TEMPERATURE_READING integer ;
alter table CUSTOMERORDERMANAGEMENT_REQUEST_LINE add column CABLING_ON_VESSEL varchar(255) ;
alter table CUSTOMERORDERMANAGEMENT_REQUEST_LINE add column FOUR_CORE varchar(255) ;
alter table CUSTOMERORDERMANAGEMENT_REQUEST_LINE add column LOT_NUMBER varchar(255) ;
alter table CUSTOMERORDERMANAGEMENT_REQUEST_LINE add column TEMPERATURE_START integer ;
